spring.application.name=travel-booking-api
server.port=8081
server.servlet.context-path=/
spring.datasource.url=jdbc:postgresql://localhost:5432/travel_booking
spring.datasource.username=postgres
spring.datasource.password=0311
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.root=INFO
logging.level.com.travelapi=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/travel-booking-api.log
spring.jackson.serialization.indent-output=true
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-exception=false
